language: node_js
node_js:
  - lts/*
services:
- docker
script:
- docker build -t dmitriiz/robotles .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push dmitriiz/robotles;
  fi